# Generated by Django 3.0.9 on 2022-11-26 03:40

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.upload_to)),
            ],
        ),
    ]
